version: "3.8"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    user: "chisanucha_kim:chisanucha_kim"
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=helloermine.com
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=<extradomains> #optional
      - STAGING=false #optional
    volumes:
      - ./config:/config
      - ./build:/config/www
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
