version: '3.7'
services: 
  web:
    container_name: nginx
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./config:/etc/nginx/
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80 
