version: "3.8"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1002
      - URL=helloermine.com
      - VALIDATION=dns
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=<extradomains> #optional
      - STAGING=false #optional
    volumes:
      - ./config:/config
      - ./build:/config/www
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
