# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ testinfra ]
    
jobs:
  build:

    runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose down
    - run: docker rmi quay.io/chisanuchakim/helloermine-web:latest
    - run: npm i
    - run: npm run build
    - run: docker build -t helloermine-web -f Web.Dockerfile .
    - run: docker tag helloermine-web quay.io/chisanuchakim/helloermine-web
    - run: docker push quay.io/chisanuchakim/helloermine-web
    - run: docker-compose up -d 
